### ISSUE TITLE
Multiple Live Agent thumbnails

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-Android#100]
1. SDK version: 214.0.2, Live agent chat version: 3.1.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: Android 9
4. Device: Google Pixel 2 XL
5. Steps to reproduce:

1) Customer Initiate a chat and is connected to Live Agent 
2) Agent click 'End chat' 
3) On customer side, 'Chat session ended by agent' appear on the screen
4) Customer minimize chat page, chat icon is grey with 'Chat Ended' under icon
5) Customer click on 'Live Agent' again to initiate a chat, WITHOUT closing the previous chat icon.
6) New thumbnail popped up, the old thmbnail is still present.

6. Actual behavior: New thumbnail is created, old one is still existing
7. Expected Behavior: Only one thumbnail is present at a time

**Comment by rileymacdonald-sf** [comment]
@JinTiloganart unfortunately this is a known issue with the minimized view. We're tracking this issue internally.

**Comment by JinTiloganart** [comment]
Hi @rileymacdonald-sf , the inactive thumbnail can't be closed either, is this a known issue too? thanks!

**Comment by JinTiloganart** [comment]
Hi @rileymacdonald-sf ,

Can you help clarify where can I try this on the sample application?
So far we only try it on our app.

Thanks!

**Comment by rileymacdonald-sf** [comment]
@JinTiloganart Clone this repository and [open this project](https://github.com/forcedotcom/ServiceSDK-Android/tree/master/Examples/SnapinsSDKExample). The [README](https://github.com/forcedotcom/ServiceSDK-Android/blob/master/Examples/SnapinsSDKExample/README.md) contains instructions on building/configuring the sample application with your Salesforce org details.
