### ISSUE TITLE
Live Chat session doesn't trigger case creation

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-Android#101]
1. SDK version: 214.0.2Live agent chat version: 3.1.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: Android 9
4. Device: Google Pixel 2 XL
5. Steps to reproduce:

1) Customer with existing account in Salesforce initiate chat from Android device. Chat is routed to Agent A
2) From Agent A side, Live Chat Transcript 01 is created, Case 01 is popped up next to Live chat transcript chat. Live Chat Transcript 01 is automatically associated with Case 01
3) Agent ends the chat.
4) The same customer initiate another chat from Android device.
6) Chat is routed to Agent B
7) From Agent side, Live Chat Transcript 02 is created, Case 01 is popped up next to Live chat transcript chat. Live Chat Transcript 02 is ALSO associated with Case 01
 
6. Actual behavior:  Live Chat Transcript initiated by the same customer is added to the same existing case.
7. Expected Behavior: When a new chat session is initiated (Live Chat Transcript02), it should always create a new case (Case 02) and associate Live Chat transcript to it.
 
8. Error Log:
 
9. Additional info:
- Version of your developer tool: Android Studio 3.2
- What language they are using: Kotlin

Sample code is attached
[Android Sample code.txt](https://github.com/forcedotcom/ServiceSDK-Android/files/2537164/Android.Sample.code.txt)

**Comment by rileymacdonald-sf** [comment]
@JinTiloganart This functionality appears to be working as expected. See the API reference at https://forcedotcom.github.io/ServiceSDK-Android/releases/chat/3.2.0/api/reference/com/salesforce/android/chat/core/model/ChatEntityField.Builder.html:

doFind(): Define whether or not this ChatEntityField will perform a lookup query for records that match the ChatUserData value within the specified Salesforce object field.

isExactMatch(true): Define whether or not the lookup should match Salesforce record results based on an exact match with the value provided by ChatUserData.

If you remove doFind(true) and isExactMatch(true) I assume a new case will be created as expected.
