### ISSUE TITLE
Live Agent Timeout not working

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-Android#102]
1. SDK version: 214.0.2, Live agent chat version: 3.1.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: Android 9
4. Device: Google Pixel 2 XL
5. Steps to reproduce:

1) In 'Chat Buttons and Automated Invitations' ,configure 'Customer Time-Out (seconds)' to 90 seconds
2) Initiate chat on Android device
3) Chat got routed to agent
4) Agent send message to customer
5) Customer leave the app open in the foreground for 5 mins
6) leave the app in the background for 5 mins
7) Chat session is still active
 
6. Actual behavior: Chat session never gets terminated, even after 10 mins
7. Expected Behavior: Chat session is terminated after customer is inactive for 90 secs from Agent's last reply.

**Comment by evanisnor** [comment]
Hi @JinTiloganart, this timeout mechanism is not supported by the Snap-Ins Android SDK at this time.

Cheers!
Evan
