### ISSUE TITLE
Accessing Visualforce page from external site/app

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-Android#103]
We would like to call a visualforce page or lightning component from our app (outside Salesforce instance). 

It's a post-chat survey page that capture the result and link it to its main case/chat. Now it's working on PC but we want this page to be accessible from mobile app as well (we're using Snap-ins SDK on mobile), to store all post-chat survey like PC.

Appreciate any advice on how to do it. 

SDK version: 214.0.2
Live agent chat version: 3.1.0

**Comment by sthistle** [comment]
Hi @JinTiloganart 
This example project shows how to monitor for the end of a chat and take some action in the app. In this example the app will launch a webview to a survey after the chat is completed. You may be able to use this as a starting point for your usecase.
https://github.com/forcedotcom/ServiceSDK-Android/tree/master/Examples/SnapinsChatSurvey

**Comment by evanisnor** [comment]
Please contact Customer Success for additional help.

Cheers,
Evan
