### ISSUE TITLE
Chat UI not closing on tapping close button

### ISSUE THREAD

**Issue by RahulSengupta13** [forcedotcom/ServiceSDK-Android#117]
### Issue Description
On closing the chat window after an agent ends the chat session, it brings the floating chat UI into view. The user has to click the `X` again on the floating component to close it. I'd like the UI to be gone completely once the user taps `X` on the chat window after an agent ends the session.

### Reproduction steps
1. Start chat session from app with agent.
2. Wait for agent to end the chat session.
3. Tap `X` to close the chat window.
4. Observe the floating chat bubble pop up.

### Version of SDK components being used
`com.salesforce.service:chat-ui:3.1.0`

### Device(s) and version(s) of Android being used
Reproducible on Android API versions 23 and up.
Devices tested on: Pixel 3, Pixel 2 XL

**Comment by rileymacdonald-sf** [comment]
@RahulSengupta13 unfortunately this functionality is not supported by the chat SDK.
