### ISSUE TITLE
Cannot transfer file

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-Android#118]
1. Version of Mobile SDK Used: 214.0.2Live agent chat version: 3.1.0

2. Issue found in Native App or Hybrid App: Native app

3. OS Version: Android 9

4. Device: Google Pixel 2 XL

5. Steps to reproduce:

1)Have the Agent send a request for a file for customer to attach
2)Get an error message 'Cannot request a file transfer'

OR

1)Have the Agent send a request for a file for customer to attach
2)Customer upload the file to the chat window and try to send it 
3)Customer selected a file to upload but fail to be uploaded
4)Receive error 'File transfer failed'

6. Expected Behavior: Agent can request for a file transfer
7. Actual behavior: Agent cannot submit a file transfer request

8. Error Log: Cannot request a file transfer

9. Additional Info: 
- Agents have tried using Chrome, IE and Firefox browser
- The issue happens intermittently

**Comment by evanisnor** [comment]
Hi @JinTiloganart, thanks for posting.

This seems to be related to your Live Agent Org configuration and does not appear to be related to the Snap-Ins Android SDK. Please contact your customer success representative about this for further assistance.

**Comment by JinTiloganart** [comment]
@evanisnor  more info on the issue, 
- it happens intermittently, not all the time
- we already enabled agent file transfer

![image](https://user-images.githubusercontent.com/44631258/51883823-9bbb9b80-23bf-11e9-8979-4d552f0e260f.png)
