### ISSUE TITLE
Not able to get chat request in Live agent

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [forcedotcom/ServiceSDK-Android#129]
Hi I have been trying to create a live agent chat session, but every time I'm getting **connecting to chat** state in the floating chat UI and after sometime the message in the chatUI change to **session suspended**. I have been following from [this document](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_chat_basic_setup.htm). Please let me know if I'm missing anything from here.

**Comment by ashand-sf** [comment]
Please see the bug template and supply the requested information. This channel is for bug reports. If you are having an integration issue, please reach out to your support agent.

Thanks!
