### ISSUE TITLE
Account is being logged in Account Settings in user's device (Android)

### ISSUE THREAD

**Issue by johndcclm** [forcedotcom/ServiceSDK-Android#137]
We have an application does not directly interact with the Android framework AccountManager in any way.

The application authenticates with Salesforce by extending the provided OAuthWebviewHelper class. This class ends up calling the Salesforce SDK's ClientManager which calls AccountManager.addAccountExplicitly. This results in account details showing up in device system settings.

Is there is a way to avoid the app from accessing AccountManager.addAccountExplicitly which causes the issue.
![android](https://user-images.githubusercontent.com/50223417/57340590-06236b00-7169-11e9-94c8-45c0e4e0276b.png)

**Comment by plangstrom** [comment]
Hi @johndcclm, this sounds to be about the Mobile SDK rather than the Service SDK. Please ask on their GitHub Issues page: https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues
Thanks!
