### ISSUE TITLE
URGENT: SF push notification is not working for auto responses when a case is created or a case is closed 

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/ServiceSDK-Android#138]
### Issue description
When a case is created using our app, there is an auto response that will be sent to the user in the app. This auto response must also have a push notification.
But the push notification is not working for the auto response.

Actual behavior:
Push notifications is not working on the auto responses when a case is created/closed.
It is only working when there is an adhoc reply from Salesforce to the app.

Expected Behavior:
Push notifications is working on the auto responses when a case is created/closed and when there is an adhoc reply from Salesforce to the app.

This is urgent as we can't continue on the release unless this is fixed.

### Reproduction steps
Create case through the app.

### Version of SDK components being used
MobileSDK 7.0.0 + ServiceSDK 216.0.1

### Device(s) and version(s) of Android being used
•	Google Pixel on Android 9.0 
o	appVersion: 2.13.1.2061
•	Samsung S8+ on Android 7.0
o	appVersion: 2.13.1.2061
•	 Samsung Galaxy A5 on Android 6.0.1
o	appVersion 2.13.0.2004
•	Oppo F1s on Android 5.1
o	appVersion: 2.13.1.2069

**Comment by plangstrom** [comment]
@geekandt As mentioned on the iOS issue for this https://github.com/forcedotcom/ServiceSDK-iOS/issues/81 we don't currently support push notifications when creating/closing cases. But as a workaround, you can try using the QuickAction API to set up a custom Apex trigger for the case publisher to automatically make posts on the case when the case changes status to created or closed. The posts on the case could send push notifications to the SDK just like the agent posts do.

https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_quickaction_quickactionrequest.htm

Hope that helps!

**Comment by geekandt** [comment]
Hi @plangstrom , This is the current functionality in our app. We already have a custom code that will post in the case chatter feed for the open and closed cases. But, we are not receiving the push notifications for this.

Please advise?
