### ISSUE TITLE
Android SDK - 2 issues detected upon upgrading to Android ServiceSDK version 218

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/ServiceSDK-Android#139]
Issue description:

Issue 1
Our android devs have tried upgrading to https://github.com/forcedotcom/ServiceSDK-Android/releases version 218.0.0
However the issue is it is not loading the existing cases once upgraded (at least in staging).
 
Actual: There's a 'Sorry Something went wrong' error on the screen.  
Expected: List of existing cases

Issue 2
When creating a case in the SF-controlled UI page, the dropdown picker misbehaves – sometimes it appears and disappears without the user being able to tap anything in the list. The behaviour is very inconsistent and not what you would expect to happen. 

Note:
•	The other fields do not seem to cause any issues. 
•	Only the dropdown picker called “I need help with…” has this issue
•	Tapping the dropdown picker starts the issue. The issue does not happen until the picker is clicked

Actual: The dropdown picker misbehaves. Sometimes it flickers.
Expected: The dropdown must load properly so that the user can select the value
 
Version of SDK components being used
version 218

Device(s) and version(s) of Android being used
Asus zenfone on Android 8.1
Google Pixel  on Android 9 
Samsung S8+ on Android 7 

Screenshot
Issue 1
![viber image 2019-05-10 , 11 02 28](https://user-images.githubusercontent.com/45929577/57504417-f18cd180-7326-11e9-94db-7b3289dadaf6.jpg)

**Comment by shanecinense1994** [comment]
Hi,

Is there any update for this?
Note that this is an urgent case on our end.
Kindly take a look on this ticket as a priority.

Thank you

Regards,
Shane

**Comment by aeisses** [comment]
Hey Shane,

We just released a new version of the SDK, can you give that a try?

Thanks,
Aaron

**Comment by colinmacdonald** [comment]
Hi Shane,

Thank you for the report. I've reproduced the upgrade bug when upgrading from 216 to 218/220 and logged a bug. Still looking into what causes this to happen.

**Comment by geekandt** [comment]
Hi @aeisses, Thank you. I have relayed to our devs regarding this new version. We'll update you once they are done building with this version.

Hi @colinmacdonald , Thank you. Looking forward to your updates. 

Thanks,
Gee

**Comment by colinmacdonald** [comment]
@shanecinense1994 @geekandt We have a fix for the Sorry "Something went wrong' error" when upgrading from 216 and are aiming to patch this fix into our 220 release next week. This issue is due to upgrading sqlCipher from 3.5.9 (216.0.0) to 4.0.1 (218.0.0+). You can override the sqlCipher version in 218.0.0+ back to 3.5.9 as a temporary workaround to prevent the error screen. However, there is a known security vulnerability in that version of sqlCipher so it's best to just upgrade once we release the patch. Thanks!

**Comment by shanecinense1994** [comment]
Thanks @colinmacdonald . Just a followup question, what is the exact date of your 220 release this week?

**Comment by colinmacdonald** [comment]
@shanecinense1994 We are planning on it being available by Friday. Could be sooner than that though. I'll be sure to post here once it's available.

**Comment by shanecinense1994** [comment]
Thank you for the info @colinmacdonald . We're looking forward for your updates.

**Comment by shanecinense1994** [comment]
Hi @colinmacdonald , just a gentle followup regarding the 220 release. Do you have any updates? Thank you

**Comment by colinmacdonald** [comment]
@shanecinense1994 The patch release is being pushed to next week due to the ongoing production issue in Salesforce. More information about this issue can be found here: https://trust.salesforce.com/en/ and here: https://status.salesforce.com/incidents/3815. I'll let you know here when it's live. Sorry for the inconvenience.

**Comment by shanecinense1994** [comment]
@colinmacdonald Thanks for the info. We're looking forward for your updates soon.

**Comment by colinmacdonald** [comment]
@shanecinense1994 Release 220.1.0 with the upgrade fix is planned to go live Wednesday, May 22th. Thanks.

**Comment by shanecinense1994** [comment]
@colinmacdonald Is it today? 29th May?

**Comment by colinmacdonald** [comment]
@shanecinense1994 Yes later today. Just had a typo in the date.

**Comment by colinmacdonald** [comment]
@shanecinense1994 The 220.1.0 release is available. For version information see here: https://github.com/forcedotcom/ServiceSDK-Android/releases/tag/220.1.0. This should address the upgrade issue you encountered. A bug has been logged for the other issue around the UI dropdown picker and is still being looked into. 

Let me know if you have any issues upgrading. Thanks!
