### ISSUE TITLE
Missing "allowMinimization" Flag 

### ISSUE THREAD

**Issue by hmedat** [forcedotcom/ServiceSDK-Android#140]
How i can remove or hide the minimize button in the chat window, 
I've checked all fields in the ChatConfig and ChatChatUiConforgrion, there is nothing 

But this flag is there in the IOS, "SCSChatConfiguration
![Screen Shot 2019-05-23 at 10 46 26 AM](https://user-images.githubusercontent.com/4534097/58231564-62c97d00-7d48-11e9-8f9b-e2fce306c2d7.png)
"

**Comment by aeisses** [comment]
Hey @hmedat 

That is not a feature that is support on Android.

Thanks,
Aaron
