### ISSUE TITLE
Android SDK - UI Dropdown picker issue when upgrading to Android ServiceSDK version 218

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/ServiceSDK-Android#145]
Issue description:
We have already logged this few weeks now but the ticket has been closed. Since this is not yet fixed, we need to create a new ticket for this to check for any updates

Previous ticket: https://github.com/forcedotcom/ServiceSDK-Android/issues/139

Issue:
When creating a case in the SF-controlled UI page, the dropdown picker misbehaves – sometimes it appears and disappears without the user being able to tap anything in the list. The behaviour is very inconsistent and not what you would expect to happen.

Note:
•	The other fields do not seem to cause any issues.
•	Only the dropdown picker called “I need help with…” has this issue
•	Tapping the dropdown picker starts the issue. The issue does not happen until the picker is clicked

Actual: The dropdown picker misbehaves. Sometimes it flickers.
Expected: The dropdown must load properly so that the user can select the value

Version of SDK components being used
version 218

Device(s) and version(s) of Android being used
Asus zenfone on Android 8.1
Google Pixel on Android 9
Samsung S8+ on Android 7

Video for the issue:
[Android - Salesforce Form page dropdown erratic.zip](https://github.com/forcedotcom/ServiceSDK-Android/files/3234717/Android.-.Salesforce.Form.page.dropdown.erratic.zip)

**Comment by colinmacdonald** [comment]
Can you try reproducing this issue on the latest 220.1.0 patch. Also, are you able to reproduce the issue without overriding any styles? Thanks.

**Comment by shanecinense1994** [comment]
Thanks @colinmacdonald , We have relayed this on our team. We'll update you as soon as we get a response from our dev team.

**Comment by shanecinense1994** [comment]
Hi @colinmacdonald  this is to inform you that the issue regarding the drop down picker is now resolved in the 220 release. Thank you for your help.

**Comment by colinmacdonald** [comment]
Thanks for looking into this @shanecinense1994 !
