### ISSUE TITLE
Salesforce Chat SDK - Camera permission is required even before logging into App

### ISSUE THREAD

**Issue by imvjhere** [forcedotcom/ServiceSDK-Android#146]
### Issue description
We are using Salesforce Chat SDK (220.0.0) in our Android app. Since the Camera permission is required for Chat SDK, the camera permission alert pops-up even before the user can login and before we can explain to the user why the permission is needed. Is there any way we can remove this permission requirement ? Or is there a way we can populate the alert only before the permission is actually needed, which is before a file transfer request ?

### Reproduction steps
Just build the SDK with the app and launch the app. 
App shows Camera/ Media permission alert.

**Comment by colinmacdonald** [comment]
I am not able to reproduce this issue as you describe. I ran the example app located in this repo and it only requests permissions for the camera when you select "take a picture" after the file is requested by an agent.

**Comment by colinmacdonald** [comment]
Also, can you post more details about the device you're using (API version)?

**Comment by imvjhere** [comment]
@colinmacdonald I am using API Version 28, and device Pixel X, Android 9.0. 
The issue exists, I assume the Salesforce Chat SDK writes the permission requirement during runtime, wondering how to make permission requirement only when selecting 'take a picture' option is selected. 

Due to this issue we had to remove the Salesforce SDK. If this is only happening in our App, Please let us know if there is any pointer, that we could fix from our side.

**Comment by imvjhere** [comment]
One thing to point is, We are using only Salesforce - ServiceChat SDK.

**Comment by colinmacdonald** [comment]
@imvjhere We only request the camera when the agent requests an attachment and the camera option is selected. We have not had other customers run into this issue. The only time I see the permission being requested is when I click the camera option for a file upload.
