### ISSUE TITLE
[URGENT] Unable to Authenticate to Salesforce

### ISSUE THREAD

**Issue by shanecinense1994** [forcedotcom/ServiceSDK-Android#147]
Issue:
We're unable to Authenticate the new/returning user to Salesforce.

Steps:
- Authenticate into the app as a new or returning customer
- Click on 'Get In Touch'

Actual:
- The unauthenticated form is loaded
- Customer is not authenticated into Salesforce
- Due to this they will never receive in-app notifications, replies and case list
- This issue is present only in Staging and not in Production

Expected:
- Customer account must be authenticated to Salesforce
- Once the user clicks on 'Get In Touch', the case list (or empty state) must be displayed
- Customer must be able to raise authenticated cases and receive notifications/replies

Version of SDK components being used
version 220

Device(s) and version(s) of Android being used
Asus Zenfone 8.1.0

**Comment by colinmacdonald** [comment]
> This issue is present only in Staging and not in Production

You will need to open a Salesforce support ticket to investigate configurations that are org related as these GitHub issues are only for issues with the Service SDKs themselves.  If your staging org is a sandbox you will want to make sure your login endpoint is pointing to `test.salesforce.com`.
