### ISSUE TITLE
Cannot Transfer File in Live Chat

### ISSUE THREAD

**Issue by ShopeeLiWenxin** [forcedotcom/ServiceSDK-Android#150]
Hi we're having an issue with our live chat functionality - transfer file in live chat session. Intermittently we got error message 'File transfer failed' after customer uploaded the file. Already talked to SF support, and provided console log, ping, HAR, traceroute, but seems not related to internet connection. So we're not sure whether there is any issue with our Snap-in SDK implementation

Version of Mobile SDK Used: Snap-in SDK version 218.0.1
Issue found in Native App or Hybrid App: Native app
OS Version: Android
Device:  samsung SM-N910C, OPPO, etc
Steps to reproduce:
1)Have the Agent send a request for a file for customer to attach
2)Customer upload the file to the chat window and try to send it
3)Customer selected a file to upload but fail to be uploaded
4)Receive error 'File transfer failed'

6.Expected Behavior: Agent can request for a file transfer

7.Actual behavior: Agent cannot submit a file transfer request

8.Error Log: Cannot request a file transfer

9.Additional Info:
Agent has "file transfer enabled" checked
The issue happens intermittently

**Comment by ShopeeLiWenxin** [comment]
Hi please do not close this case as we need to collaborate with our dev and Salesforce support here

**Comment by colinmacdonald** [comment]
@ShopeeLiWenxin I need some clarification around the reproduction steps.

In your steps you describe 
> 1)Have the Agent send a request for a file for customer to attach
> 2)Customer upload the file to the chat window and try to send it
> 3)Customer selected a file to upload but fail to be uploaded
> 4)Receive error 'File transfer failed'

But you also describe the expected and actual results as:
> 6.Expected Behavior: Agent can request for a file transfer
> 
> 7.Actual behavior: Agent cannot submit a file transfer request

Which one of these statements best describes what's happening (This assumes you're using the default UI):

A. The agent attempts to request a file transfer in the service console but the request fails and never makes it to the device.

*OR*

B. The agent successfully requests the file transfer. The attach file icon appears (camera icon). However, after the end user clicks the icon to select an attachment it fails to upload the attachment.

Thanks,
Colin

**Comment by colinmacdonald** [comment]
Also, Can you please confirm this is an issue on both iOS and Android? I believe at first I only saw an issue open for iOS but now there's one for both platforms.

**Comment by ShopeeLiWenxin** [comment]
Hi Colin, 

Thanks for following up on the case here. The issue we're facing is B:
B. The agent successfully requests the file transfer. The attach file icon appears on the device (camera icon). However, after the end user clicks the icon to select an attachment it fails to upload the attachment from the device.

In addition, after agent successfully requests the file transfer and end-user selected the file for upload. the file upload % blue bar will go all the way to the right then pop up an error message: file transfer failed. 

Hope this clarifies. Thanks!
Wenxin

**Comment by colinmacdonald** [comment]
Thanks for the clarification @ShopeeLiWenxin. I compared the logs for all of our customer's orgs to your org to and do see a significantly higher rate of failure when attempting to attach a file. Some failures are expected due to variable network conditions but your org does see a higher failure rate.

I have a few follow up questions:

1. Do you experience the issue on both iOS & Android or is it mostly just one or the other?
2. I see your first case describing this issue was opened in December. Did this feature work correctly before that?
3. Have you tried using this feature on other networks just to be sure there's not a firewall rule blocking some requests?
4. Can you try updating the SDK you're using to the latest?
 - Android: https://github.com/forcedotcom/ServiceSDK-Android/releases/tag/220.1.0
 - iOS: https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/220.1.0
5. To isolate whether this is an issue specifically with your implementation can you try our example apps (configured for your environment) located https://github.com/forcedotcom/ServiceSDK-Android and https://github.com/forcedotcom/ServiceSDK-ios and try using the feature again?
6. Lastly, can you try using the feature on another org like a sandbox org?

I appreciate your patience as this kind of issue is very difficult to reproduce due to there being so many variables at play.

Thanks,
Colin

**Comment by ShopeeLiWenxin** [comment]
Hi @colinmacdonald ,

Please find my comments below.

Do you experience the issue on both iOS & Android or is it mostly just one or the other?
**>> When the issue happens, we experience it on both iOS and Android**
I see your first case describing this issue was opened in December. Did this feature work correctly before that?
**>> We only started using chat SDK in Dec last year and the issue started after that**
Have you tried using this feature on other networks just to be sure there's not a firewall rule blocking some requests?
**>>We have 7 countries using this feature, all countries have constantly experience this issue.** 
Can you try updating the SDK you're using to the latest?
Android: https://github.com/forcedotcom/ServiceSDK-Android/releases/tag/220.1.0
iOS: https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/220.1.0
**>> Sure will work with our developer to try the latest version**
To isolate whether this is an issue specifically with your implementation can you try our example apps (configured for your environment) located https://github.com/forcedotcom/ServiceSDK-Android and https://github.com/forcedotcom/ServiceSDK-ios and try using the feature again?

**>> Do you have any instruction on how do we use the example apps to try this feature?**

Lastly, can you try using the feature on another org like a sandbox org?

**>> Currently we're not able to implement SDK in our app and connect it to sandbox, is there any sample app we can embed the code and use this feature in our sandbox?**

**Comment by colinmacdonald** [comment]
> Do you have any instruction on how do we use the example apps to try this feature?

Yes, can be found here in the README: 
 - Android: https://github.com/forcedotcom/ServiceSDK-Android/tree/master/Examples/SnapinsSDKExample
 - iOS: https://github.com/forcedotcom/ServiceSDK-iOS/tree/master/Examples/SnapinsSDKExample.

Will just need to configure the sample apps with your live agent server URL, organizationId, deploymentId, and buttonId. It's the same as how you configured your production app with the SDK. Then you should be able to just start a chat session as normal.

> Currently we're not able to implement SDK in our app and connect it to sandbox, is there any sample app we can embed the code and use this feature in our sandbox?

Yes, you can use the same sample apps I described above and configure it with your sandbox org's live agent server URL, organizationId, deploymentId, and buttonId.

**Comment by ShopeeLiWenxin** [comment]
Hi Colin,

Just to check again, in order to use the sample apps here, we need to have some Android & iOS testing apps to implement the sample app code, is that correct? I have consulted our developer and seems we need a mobile app in order to try the sample you shared above.

**Comment by ShopeeLiWenxin** [comment]
Hi Colin,

Regarding the SDK version, we're constantly updating the SDK version to the most updated one but the issue still persists.

**Comment by colinmacdonald** [comment]
Hi @ShopeeLiWenxin, 

> Just to check again, in order to use the sample apps here, we need to have some Android & iOS testing apps to implement the sample app code, is that correct? I have consulted our developer and seems we need a mobile app in order to try the sample you shared above.

Nope, the example app I linked above is a complete app that you can run by itself. 

You can see this is just the root of a regular Android project that you can import into Android Studio, build, and run: https://github.com/forcedotcom/ServiceSDK-Android/tree/master/Examples/SnapinsSDKExample. The same goes for the iOS sample app. Can import it into Xcode, build, and run: https://github.com/forcedotcom/ServiceSDK-iOS/tree/master/Examples/SnapinsSDKExample

> Regarding the SDK version, we're constantly updating the SDK version to the most updated one but the issue still persists.

Thank you for checking into this.

**Comment by ShopeeLiWenxin** [comment]
Hi Collin,

Just wanna check with you again, when you compare our org's file transfer failure rate with other companies, are you comparing with companies that use snap-in SDK specifically? Thanks!

Best regards,
Wenxin

**Comment by colinmacdonald** [comment]
Hi @ShopeeLiWenxin,

Yes, I compared your org's failure rate to all of our other customers using the Snap-Ins chat SDK.

**Comment by colinmacdonald** [comment]
Issue has been inactive for a month. Closing.
