### ISSUE TITLE
Android Salesforce SDK is not allowing tappable phone number links on OS 9

### ISSUE THREAD

**Issue by TooSerious** [forcedotcom/ServiceSDK-Android#151]
When reporting a bug:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### Issue description
When Salesforce agent sends a phone number to a user of their service over an Android OS 9 device, the user does not see the phone number as a tappable link.

Expected Results: User should be seeing the phone number sent as a linked number and tapping on it should open the call screen with the number pre-populated

Actual Results: User is seeing the number as just plain text with no tapping functionality.

### Reproduction steps
1.) Log into a Salesforce account on web and any services that use the Salesforce chat system

2.) Initiate a chat between agent and user

3.) Have the agent send a valid phone number to the user

4.) Observe that the user is not seeing the phone number sent as a link and tapping on it doesn't not open the devices call screen.

### Version of SDK components being used
com.salesforce.service:chat-ui:3.5.0

### Device(s) and version(s) of Android being used
Devices: #444 GS9+ OS 9, Samsung Galaxy S10 (OS 9), Pixel 3 XL OS 9.0
![device-2019-07-02-110012](https://user-images.githubusercontent.com/52719068/60919549-ae35dd00-a25b-11e9-84ae-990893a67811.png)

### Screenshots / Videos
Attached

**Comment by colinmacdonald** [comment]
@TooSerious Thank you for the detailed bug report. I will open an internal bug report referencing this issue where it will be prioritized for a future release.
