### ISSUE TITLE
Chat UI End Session Alert Dialog not following app theme color

### ISSUE THREAD

**Issue by Maxwell6635** [forcedotcom/ServiceSDK-Android#152]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2 , ChatUI 3.5.0
2. Issue found in Native App or Hybrid App: End Chat Session Alert Dialog Color is not following App Theme Color.
3. OS Version: Android 7 (Nougat)
4. Device: Huawei P9 Plus

5. Steps to reproduce: Start A Live Agent Chat, minimise ] the live chat session and press cross button it will prompt end session alert dialog and the button background for cancel and ok button is white color

6. Actual behavior:  alert dialog and the button background for cancel and ok button is white color 
![Screenshot_20190711-102534](https://user-images.githubusercontent.com/12591474/61018716-59fd3b00-a3ca-11e9-8ab1-5dbade5e248b.png)

7. Expected Behavior: alert dialog and the button background for cancel and ok button should follow our app theme color
![Screenshot_20190711-104452](https://user-images.githubusercontent.com/12591474/61018720-5d90c200-a3ca-11e9-96f7-c87efa962f48.png)

8. Error [Log:]

**Comment by Maxwell6635** [comment]
Hi Salesforce,

Any updates on this issues?

**Comment by colinmacdonald** [comment]
@Maxwell6635 You can do this by following this guide: https://developer.salesforce.com/docs/atlas.en-us.service_sdk_android.meta/service_sdk_android/android_customize_colors.htm

Specifically you're going to be looking to change `salesforce_brand_secondary` for the button text in this dialog, `salesforce_contrast_quaternary` for the background color, and `salesforce_contrast_primary` for the title

**Comment by colinmacdonald** [comment]
![Screen Shot 2019-07-16 at 8 49 01 AM](https://user-images.githubusercontent.com/3648226/61292061-9c49c200-a7a6-11e9-8c4e-d36474cd1581.png)

```
<color doc="The quaternary brand contrast color. Please consult the Service SDK Customization Guide for more information."
           name="salesforce_contrast_quaternary">#6A058F</color>
<color doc="The secondary brand color. Please consult the Service SDK Customization Guide for more information."
           name="salesforce_brand_secondary">#C411D1</color>
<color doc="The primary brand contrast color. Please consult the Service SDK Customization Guide for more information."
           name="salesforce_contrast_primary">#F5D400</color>
```

**Comment by Maxwell6635** [comment]
@colinmacdonald 
I have tried still not working. Kindly refer to this video 
https://drive.google.com/open?id=1-IkkOltWcZ6Znq8IWvtO7PJsFjIiN_Zp

**Comment by colinmacdonald** [comment]
@Maxwell6635 I can't say for sure what's happening on your end but there must be some style override you're missing as part of your theme. If you try running the example app located in this repo: https://github.com/forcedotcom/ServiceSDK-Android/tree/master/Examples/SnapinsSDKExample and add the following to https://github.com/forcedotcom/ServiceSDK-Android/blob/master/Examples/SnapinsSDKExample/app/src/main/res/values/colors.xml

```
<!-- ======================================================================================= -->
    <!-- BRAND COLORS -->

    <color name="salesforce_brand_primary" doc="The primary brand color. Please consult the Service SDK Customization Guide for more information.">
        #2EBD59
    </color>

    <color name="salesforce_brand_secondary" doc="The secondary brand color. Please consult the Service SDK Customization Guide for more information.">
        #27A34C
    </color>

    <color name="salesforce_brand_primary_inverted" doc="The primary brand contrast color. Please consult the Service SDK Customization Guide for more information.">
        #FCFCFC
    </color>

    <color name="salesforce_brand_secondary_inverted" doc="The secondary brand contrast color. Please consult the Service SDK Customization Guide for more information.">
        #FBFBFB
    </color>

    <!-- ======================================================================================= -->
    <!-- TOOLBAR COLORS -->

    <color name="salesforce_toolbar" doc="The toolbar background color. Please consult the Service SDK Customization Guide for more information.">
        #010101
    </color>

    <color name="salesforce_toolbar_inverted" doc="The toolbar contrast color, used primarily for text shown on a toolbar. Please consult the Service SDK Customization Guide for more information.">
        #FAFAFA
    </color>

    <!-- ======================================================================================= -->
    <!-- CONTRAST COLORS -->

    <color name="salesforce_contrast_primary" doc="The primary brand contrast color. Please consult the Service SDK Customization Guide for more information.">
        #FFFFFF
    </color>

    <color name="salesforce_contrast_secondary" doc="The secondary brand contrast color. Please consult the Service SDK Customization Guide for more information.">
        #F4F4F4
    </color>

    <color name="salesforce_contrast_tertiary" doc="The tertiary brand contrast color. Please consult the Service SDK Customization Guide for more information.">
        #333333
    </color>

    <color name="salesforce_contrast_quaternary" doc="The quaternary brand contrast color. Please consult the Service SDK Customization Guide for more information.">
        #444444
    </color>

    <color name="salesforce_contrast_inverted" doc="The inverted brand contrast color. Please consult the Service SDK Customization Guide for more information.">
        #1E1E1E
    </color>

    <!-- ======================================================================================= -->
    <!-- FEEDBACK COLORS -->

    <color name="salesforce_feedback_primary" doc="The primary feebdack brand color. Please consult the Service SDK Customization Guide for more information.">
        #E74C3C
    </color>

    <color name="salesforce_feedback_secondary" doc="The secondary feedback brand color. Please consult the Service SDK Customization Guide for more information.">
        #2ECC71
    </color>

    <color name="salesforce_feedback_tertiary" doc="The tertiary feedback brand color. Please consult the Service SDK Customization Guide for more information.">
        #F5A623
    </color>

    <!-- ======================================================================================= -->
    <!-- OVERLAY COLORS -->

    <color name="salesforce_overlay" doc="The background brand color. Please consult the Service SDK Customization Guide for more information.">
        #AAFFFFFF
    </color>
```

I see this: 

minimized view close:

![Screen Shot 2019-07-16 at 10 44 21 AM](https://user-images.githubusercontent.com/3648226/61299564-b390ab80-a7b6-11e9-8678-6192577675b4.png)

fullscreen close:

![Screen Shot 2019-07-16 at 10 44 50 AM](https://user-images.githubusercontent.com/3648226/61299599-c905d580-a7b6-11e9-8c4d-40e6e59c00cf.png)

Make sure to override all of those values with your designed theme and it should look correct. You can drop those colors into your app and see if that at least overrides all the colors as expected. Let me know how that turns out for you.

**Comment by Maxwell6635** [comment]
@colinmacdonald 
Hi I found the reason that why is not being follow the salesforce custom color. Reason is I am using MaterialDesign Theme Style thus it will overwrite all alert dialog button text color. I have tested out in using example the result is same as I facing the issues. 
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">

Could you kindly check why when we not able to use Material Theme with Salesforce ChatUI ?

**Comment by colinmacdonald** [comment]
@Maxwell6635 Sorry, we can't test all design themes to make sure they are compatible with our out of the box UI. You will have to override some of the colors being set by MaterialDesign.
