### ISSUE TITLE
Live Chat File Transfer attach pdf files with ChatUI 

### ISSUE THREAD

**Issue by Maxwell6635** [forcedotcom/ServiceSDK-Android#153]
May I know how can I enable for Android able to send pdf attachment instead image only ?

As now Agent request file transfer only camera attachment icon is available, but user unable to send any file or pdf to Live Agent.

**Comment by colinmacdonald** [comment]
@Maxwell6635  Currently we only provide access to image directories on IOS and Android in the default UI. This may be possible to implement using the core API (not using our default API). I'll open this as a feature request for the default UI where it would have to be prioritized for a future release.

**Comment by Maxwell6635** [comment]
@colinmacdonald 
Using the Core API required a lot of effort to done the UI customisation ? Could it be ChatUI default add FileTransferRequestListener ?

**Comment by colinmacdonald** [comment]
@Maxwell6635 Unfortunately not. The default ChatUI cannot be extended with this kind of functionality from Chat Core so it would have to be one or the other at the moment.
