### ISSUE TITLE
Live Chat Android Soft Keyboard Appear Again After Pressed Chat With An Agent 

### ISSUE THREAD

**Issue by Maxwell6635** [forcedotcom/ServiceSDK-Android#154]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2 , ChatUI 3.5.0
2. Issue found in Native App : After key in prechat field and start live agent, Android default soft keyboard appear again
3. OS Version: Android 7 (Nougat)
4. Device: Huawei P9 Plus

5. Steps to reproduce: 
1) Start A Live Agent Chat
2) Prechat Field Form appear and Android Soft keyboard will appear 
3) Press Android default back button, soft keyboard has been dismissed
4) Press Chat With An Agent button
5) Android Soft Keyboard appear again

6. Actual behavior:  Android Soft Keyboard appear again. Kindly refer below videos
https://drive.google.com/open?id=1-IkkOltWcZ6Znq8IWvtO7PJsFjIiN_Zp

7. Expected Behavior: Android Soft Keyboard shouldn't appear again

8. Error [Log:]

**Comment by colinmacdonald** [comment]
Thanks for the bug report. We will look into this and file an internal bug ticket.
