### ISSUE TITLE
Chat UI end session alert dialog different when minimized

### ISSUE THREAD

**Issue by denyspro** [forcedotcom/ServiceSDK-Android#155]
### Issue description
Hi. We found the end session alert colors are different when the chat window is minimized.

Maximized:
<img width="240" alt="Screen Shot 2019-07-25 at 16 20 47" src="https://user-images.githubusercontent.com/6625509/61902591-d62e6d00-aef8-11e9-9b78-feffc9a67b64.png">

Minimized:
<img width="240" alt="Screen Shot 2019-07-25 at 16 20 57" src="https://user-images.githubusercontent.com/6625509/61902609-dd557b00-aef8-11e9-9fdf-8e0d7e9ca756.png">

Our colors.xml:
`<color name="salesforce_toolbar">#242424</color> 
<color name="salesforce_toolbar_inverted">#FFFFFF</color> 
<color name="salesforce_brand_primary">#242424</color> 
<color name="salesforce_brand_contrast">#FFFFFF</color> 
<color name="salesforce_brand_secondary">#242424</color> 
<color name="salesforce_contrast_primary">#000000</color> 
<color name="salesforce_contrast_secondary">#242424</color> 
<color name="salesforce_contrast_tertiary">#494949</color> 
<color name="salesforce_contrast_quartenary">#242424</color> 
<color name="salesforce_contrast_inverted">#FFFFFF</color> 
<color name="salesforce_feedback_primary">#5B1E18</color> 
<color name="salesforce_feedback_secondary">#12502C</color> 
<color name="salesforce_feedback_tertiary">#60410E</color> 
<color name="salesforce_overlay">#66000000</color>`

### Reproduction steps
1) Start chat, then close it. Box like image 1 is shown.
1) Start chat, minimize it, then close it. Box like image 2  is shown.

### Version of SDK components being used
3.5.0

### Device(s) and version(s) of Android being used
Android 8. Samsung Galaxy 10, but it's happening in all devices really.

**Comment by colinmacdonald** [comment]
This was reported before here: https://github.com/forcedotcom/ServiceSDK-Android/issues/152. The issue was that a MaterialDesign theme was overriding some colors. Without the MaterialDesign theme applied you can see the colors show up as expected in the issue linked above.
