### ISSUE TITLE
Is it possible to customize the chat interface minimized view and queue display?

### ISSUE THREAD

**Issue by iandextermaya** [forcedotcom/ServiceSDK-Android#157]
QUESTION

Is it possible to customize the chat interface minimized view and queue display?

https://i.stack.imgur.com/BVbNv.png

Thanks!

**Comment by colinmacdonald** [comment]
Hi @iandextermaya,

It depends on what kind of customization you're looking for. 

If you simply want to change the colors to match your app's branding, yes: https://developer.salesforce.com/docs/atlas.en-us.service_sdk_android.meta/service_sdk_android/android_customize_colors.htm?search_text=branding.

If that doesn't fit your needs you can also build your own UI using our chat-core SDK: https://developer.salesforce.com/docs/atlas.en-us.service_sdk_android.meta/service_sdk_android/android_chat_core_api.htm?search_text=branding. This is obviously going to be more work than just changing a few color values but is the ultimate way to fully customize chat in your app.
