### ISSUE TITLE
Query - Push Silent Notifications

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/ServiceSDK-Android#158]
### Issue description
Our devs need to know:
1. Does the SF SDK push silent notifications to the app? Under what conditions, when does this happen?
2. And additionally can it be removed?

### Version of SDK components being used
220.1

### Device(s) and version(s) of Android being used
All devices 
Android 7 and up

**Comment by colinmacdonald** [comment]
Please see [this documentation](https://developer.salesforce.com/docs/atlas.en-us.service_sdk_android.meta/service_sdk_android/android_push_notifications.htm?search_text=notification) to see if it fits your use case. Thanks.
