### ISSUE TITLE
Application generated dialogs do not show in SOS screen sharing sessions

### ISSUE THREAD

**Issue by danmcmillen** [forcedotcom/ServiceSDK-Android#37]
Hi,

We are currently using Service Cloud Snap-Ins for Android for customer support in our android application, however it appears that dialogs created by our application do not show up in the Agent's SOS screen sharing session, when the do appear on the users android device.

We have followed relevant documentation and guides found here: https://developer.salesforce.com/docs/atlas.en-us.service_sdk_android.meta/service_sdk_android/servicesdk_android_dev_guide.htm

We are currently using SOS version 3.1.0

Thanks in advance,

Dan

**Comment by rileymacdonald-sf** [comment]
Hi Dan,

I've been unable to reproduce this issue using our test application on SOS 3.1.0. Can you clarify what type of dialog you're using to reproduce the issue?

Thanks

**Comment by danmcmillen** [comment]
Just a standard `DialogFragment` from android support lib.

**Comment by rileymacdonald-sf** [comment]
Are the dialogs in question part of the window's view hierarchy? Any dialogs out of this hierarchy will not be captured by the SOS session.

**Comment by danmcmillen** [comment]
Sorry, will have to get back to you on this. This might be the root cause, if it is not I will reopen. Thanks for the quick responses!
