### ISSUE TITLE
Minimum supported API version number is now 21?

### ISSUE THREAD

**Issue by davidmigloz** [forcedotcom/ServiceSDK-Android#42]
Is there any reason why you are dropping support for Android KitKat?

According to the [official data from February](https://developer.android.com/about/dashboards/index.html) there are still 12% of Android users using this version... which I think it's not an insignificant number.

**Comment by rileymacdonald-sf** [comment]
@davidmigloz As part of our initiative to reduce our testing overhead and focus on supporting newer versions of Android we've dropped support for KitKat in release 212.
