### ISSUE TITLE
salesforcesos.com certificate is expired

### ISSUE THREAD

**Issue by davidmigloz** [forcedotcom/ServiceSDK-Android#48]
SSL certificate of salesforcesos.com expired today.

![image](https://user-images.githubusercontent.com/6546265/39989817-46dac314-576b-11e8-9274-b210ae4449f5.png)

**Comment by evanisnor** [comment]
Hey David,

Sorry about that. We're working on renewing the certificate today. In the meantime you can replace the `salesforcesos.com` maven repository in your gradle scripts with this:

```
        maven {
            url 'http://salesforcesos.com.s3.amazonaws.com/android/maven/release'
        }
```

I'll post an update here and close the issue once the cert is renewed.

Cheers,
Evan

**Comment by evanisnor** [comment]
Looks like we won't be able to get a renewed cert and the salesforcesos.com domain is being EOL'd soon. We are in the process of updating our documentation to reference the amazonaws URL.

In case anyone missed the edit, there is an HTTPS URL available and regular HTTP access has been restricted. Please reference the following maven repository going forward:

```
maven {
    url 'https://s3.amazonaws.com/salesforcesos.com/android/maven/release'
}
```

I'll leave this issue open for a while for people to see.

cc @davidmigloz

**Comment by evanisnor** [comment]
Hi @glureau-betclic,

For security reasons we have disabled HTTP access to the s3 instance so you have to reference the repository using the HTTPS URL instead.


```
maven {
    url 'https://s3.amazonaws.com/salesforcesos.com/android/maven/release'
}
```

**Comment by glureau-betclic** [comment]
Thanks for the super fast response! I missed the new https AWS 👍
