### ISSUE TITLE
Build Error  servicesdk 212.0.0

### ISSUE THREAD

**Issue by eladyi** [forcedotcom/ServiceSDK-Android#51]
hello,
I experience build error at my project and get  the same errors at  SnapinsChatSurvey salesforce example project.
i get this errors:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.salesforce.service:servicesdk:212.0.0.

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.salesforce.service:servicesdk:212.0.0.

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.salesforce.service:servicesdk:212.0.0.

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.salesforce.service:servicesdk:212.0.0.

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.salesforce.service:servicesdk:212.0.0.

thank's
elad

**Comment by evanisnor** [comment]
Hi @eladyi , this is related to issue #48 . I'll post an update to the example projects to fix this soon. In the meantime you can update the salesforcesos.com repository to the following in Android Studio, in the root `build.gradle`:

```
maven {
    url 'https://s3.amazonaws.com/salesforcesos.com/android/maven/release'
}
```

**Comment by evanisnor** [comment]
@eladyi If you run `git pull` it should fetch the latest example update which fixes the resolution error you are seeing. Cheers!
