### ISSUE TITLE
Chat availability

### ISSUE THREAD

**Issue by miguel-duarte** [forcedotcom/ServiceSDK-Android#53]
I'm developing a mobile app using React Native to be used on Android and IOS devices. In this application I'm using the Salesforce Live Agent snapin feature. The active agent is working fine and we can establish the chat with the agents, but it is not possible to check if the agent is available or not before clicking in the chat button. When we try to use your solution to check agent availability, we receive always unavailable result.

In this developments we are using:
"react": "16.0.0",
"react-native": "0.50.4",
"salesforcemobilesdk-android": "v5.3.0"
com.salesforce.service:servicesdk:212.+

Note: I've even tried to upgrade these versions but with the same result.
"react": "16.2.0",
"react-native": "0.53.3",
"salesforcemobilesdk-android": "v6.1.0"
com.salesforce.service:servicesdk:212.+

**Comment by evanisnor** [comment]
Hi @miguel-duarte! I'm having trouble reproducing this problem. Can you confirm that your ChatConfiguration values are correct when calling `ChatCore.configureAgentAvailability(..)`?

This may also be related to your org's Live Agent configuration. Which style of routing is configured for your button?

**Comment by evanisnor** [comment]
@miguel-duarte The "Unknown" state is returned by the SDK when the server has not provided an availability status. We usually recommend treating "Unknown" with the same case as "AgentsAvailable" because the chat session may still work.

Can you confirm for me that the Live Agent Pod that gets returned in `state.getLiveAgentPod()` is the same as the pod you have configured in your BuildConfig?

**Comment by evanisnor** [comment]
Hey @miguel-duarte, I am unable to reproduce your problem, and you seem to be experiencing the same problem on iOS as well (https://github.com/forcedotcom/ServiceSDK-iOS/issues/21). When the server does not respond with an availability status the Android SDK will report `Unknown`, and the iOS SDK will report `Unavailable` by default.

This does not appear to be an issue with the SDK, but an issue with your Org's Live Agent configuration. Unfortunately I am unable to help you with matters regarding org configuration. Please contact your Salesforce support representative as they will be better equipped to help you with your problem. Alternatively you can visit the [Salesforce Success Community](https://help.salesforce.com/home) and create a new case.
