### ISSUE TITLE
Popup windows are not Showing on Agent's SOS screen during SOS Screen Sharing Session.

### ISSUE THREAD

**Issue by Shivani-Infostretch** [forcedotcom/ServiceSDK-Android#56]
Hi,

We are currently using  Service Cloud Snap-Ins API in Android for providing live customer support in our application. 
In our application we are showing some coach-marks using Android PopupWindow widget.
As per android docs, PopupWindow is a floating container that appears on top of the current activity.Hence, PopupWindow is not a part of Activity's View Hierarchy and we are not able to capture it on Agent's Sos Screen.

However , Service Cloud Snap-Ins API provides a method Sos.captureExtra(Dialog dialog) for capturing extra Dilaog Fragements which are not part of Activity's view hierarchy.

Please refer the following link. 

http://forcedotcom.github.io/ServiceSDK-Android/releases/sos/3.0.0/api/reference/com/salesforce/android/sos/api/Sos.html#captureExtra(android.widget.Toast)

We are using SOS version 3.1.0.

Is there any way for showing PopupWindow on Agent's Sos Screen Using SOS Api?

**Comment by evanisnor** [comment]
Hi @Shivani-Infostretch,

Sorry, we don't currently support PopupWindow for capture during screen sharing. This would amount to a feature request. Feel free to submit this as a feature idea on the [Success Community's Idea page](https://ideas.salesforce.com).

Cheers,
Evan
