### ISSUE TITLE
Maven repo down

### ISSUE THREAD

**Issue by AndrewBestbier** [forcedotcom/ServiceSDK-Android#58]
Hi there, it seems as though your repo is down?

https://s3.amazonaws.com/salesforcesos.com/android/maven/release

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>android/maven/release</Key>
<RequestId>896E0EAA572C0851</RequestId>
<HostId>
2WD30dyKqGFWhkoep9hU99UD9tMBntcHmhCwN+Ze35NOdI6yR5KE71dhfhhPa52S/6thoLklwH8=
</HostId>
</Error>
```

The other one has its certificate expired.

**Comment by evanisnor** [comment]
Hey @AndrewBestbier, thanks for bringing this up. Hopefully everything is working as expected now. I'm guessing our s3 instance had a bit of a service interruption. Let us know if you have any further issues!
