### ISSUE TITLE
maven repo is down 2nd time

### ISSUE THREAD

**Issue by sashalinder** [forcedotcom/ServiceSDK-Android#59]
Hi,
please assist.

https://s3.amazonaws.com/salesforcesos.com/android/maven/release

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>android/maven/release</Key>
<RequestId>7DDE75EC415F3C6A</RequestId>
<HostId>
vBQZqn00LUK0rSx4MEOiwB0Ad3NQAvUV9LP/x+UPhIlB+a6m0n4S3jzd5fXRVHvIxgHWBw1HRM8=
</HostId>
</Error>

**Comment by evanisnor** [comment]
Hey @sashalinder, are you trying to browse our maven repository in your browser? We don't allow that. If you would like to integrate one of our SDKs into your Android app, please consult our [installation guide](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_install_sdk.htm).
Cheers!
