### ISSUE TITLE
string length visible under PreChatField 

### ISSUE THREAD

**Issue by yasmcse** [forcedotcom/ServiceSDK-Android#62]
I am creating a PreChatField which is simply a text field. But at bottom|right of the textfield the length of the string is being shown. The length is variable off course as the user types.

I don't want to display this length. How shall i remove this ?

**Comment by evanisnor** [comment]
Hi @yasmcse, sorry but this feature isn't supported at the moment. It is possible to build your own custom Pre-Chat user experience by populating [ChatUserData](http://forcedotcom.github.io/ServiceSDK-Android/releases/chat/3.1.0/api/reference/com/salesforce/android/chat/core/model/ChatUserData.html) objects with the form data and passing them to a [ChatConfiguration.Builder](http://forcedotcom.github.io/ServiceSDK-Android/releases/chat/3.1.0/api/reference/com/salesforce/android/chat/core/ChatConfiguration.Builder.html#chatUserData(java.util.List%3Ccom.salesforce.android.chat.core.model.ChatUserData%3E)) when you want to start the chat. Also check out [this guide](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_chat_send_custom_data.htm) on how to use ChatUserData objects to find Salesforce records based on your pre-chat data.

Version 3.1.0 of the Chat SDK was just released, so don't forget to upgrade!

Hope this helps. Cheers!
