### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by atchariyap** [forcedotcom/ServiceSDK-Android#64]
Hi,

We tested SOS on Android but the app is closed while calling agent. The App team found this log shows that there is an error from Salesforce. 

https://drive.google.com/file/d/1KjUEkfDTkTuRnOvke3S2pxDr2zKeJIFX/view?usp=sharing

Could you please let us know what is this error and how to fix?

Thank you.

Regards,

Atchariya

**Comment by evanisnor** [comment]
Hey @atchariyap, thanks for bringing this to our attention. We're looking into this now and we will get back to you on this as soon as we can.

**Comment by evanisnor** [comment]
Hi @atchariyap, we'll have a patched version of SOS out before the end of the week. I'll post an update here with upgrade instructions once it has been made available.

**Comment by atchariyap** [comment]
Hi Evan,

Thank you for your update. So there is some bug on SOS right?

Regards,

Atchariya




Atchariya  Potduang

Project Manager

I&I Consulting Group Company Limited

475 Siripinyo Building, Unit 1801, 18Fl., Si Ayutthaya Road,

Phaya Thai, Ratchathewi, Bangkok 10400 Thailand

Phone : 063-323-8463  |  Email : acp@ii.co.th <pst@ii.co.th>  |  Website :
www.ii.co.th

[image: cert_logo-SALESFORCE-PLATFORM-APP-BUILDER.png]

**Comment by evanisnor** [comment]
Yes that is correct.

**Comment by evanisnor** [comment]
Hi @atchariyap, we've just released a patch for the issue you were seeing. Please upgrade your dependency to consume SOS version 4.0.2, or ServiceSDK 214.0.1 to get the fix. Let me know how it goes!

https://github.com/forcedotcom/ServiceSDK-Android/releases/tag/214.0.1

Cheers,
Evan

**Comment by atchariyap** [comment]
Hi Evan,

Thanks for your quick response.

Just to confirm that this release is tested and solved the issue?

Thank you.

Regards,

Atchariya


Atchariya  Potduang

Project Manager

I&I Consulting Group Company Limited

475 Siripinyo Building, Unit 1801, 18Fl., Si Ayutthaya Road,

Phaya Thai, Ratchathewi, Bangkok 10400 Thailand

Phone : 063-323-8463  |  Email : acp@ii.co.th <pst@ii.co.th>  |  Website :
www.ii.co.th

[image: cert_logo-SALESFORCE-PLATFORM-APP-BUILDER.png]

**Comment by evanisnor** [comment]
We tested the fix on a Samsung Galaxy Tab S with Android 5, which is the closest we have to the device you had reported seeing the crash on. We take crash reports very seriously here so this fix became our number one priority. Unfortunately it is not always possible for us to replicate the exact customer scenarios, but we do our best. Please let me know if you experience any further issues.

Thanks,
Evan

**Comment by atchariyap** [comment]
Hi Evan,

Thank you very much for your support.

We have sent the patch to mobile app team and will let you know if any
issue.

Regards,

Atchariya
