### ISSUE TITLE
Black (or transparent) KnowledgeUIClient Activity when app is backgrounded -> process is killed in background -> app reopened

### ISSUE THREAD

**Issue by dev777** [forcedotcom/ServiceSDK-Android#69]
### Problem
I'm seeing an issue when calling `knowledgeUiClient.launchHome` to display the salesforce Knowledge UI home activity -> backgrounding the app -> simulate process death by OS (using Dev Options - Background Process limit - No background processes) -> opening another app to have the OS kill my process -> reopen app (through Overview or Launcher).

I see either a transparent (Nexus 5X API 23 emulator) or black (Nexus 5X API 21 emulator) knowledge activity. The behavior seems to differ based on device+OS.

### Expected Result
I would expect to see the Knowledge UI displaying the same UI before process death. If that is not feasible, I would least expect the user to see the knowledge UI landing (if the user was navigating inside the knowledge experience before process death+restart).

### Workaround
The way I'm working around it is tracking if the Knowledge UI is open -> if so, closing it manually in onSaveInstanceState -> re-launch it in onCreate (according to the saved instance state bundle). This is not ideal because it must live in a BaseActivity since the SDK can be minimized and re-maximized at any time and can happen on every screen in the app.

I would love to remove this workaround when a fix is made to the sdk.

### Devices
* Nexus 5X API 23 emulator
* Nexus 5X API 21 emulator

### Salesforce SDK
4.1.0

### Screencast
I've attached a screencast of the behavior of the sample app on the Nexus 5X API 23 emulator.

[salesforce_knowledge_sample_bad_behavior_when_app_is killed_in_background_with_knowledge_ui_up.webm.zip](https://github.com/forcedotcom/ServiceSDK-Android/files/2193485/salesforce_knowledge_sample_bad_behavior_when_app_is.killed_in_background_with_knowledge_ui_up.webm.zip)

**Comment by rileymacdonald-sf** [comment]
Thanks for raising this issue @dev777, I'm able to reproduce it. I'll investigate and get back to you.

**Comment by rileymacdonald-sf** [comment]
@dev777 Thanks for raising this. I'm closing this issue for now as we've scheduled a fix for our next release.
