### ISSUE TITLE
Case/Record is not created automatically in Sales force chat agent side in live chat.

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/ServiceSDK-Android#72]
Please fill out the following details:

Version of Mobile SDK Used: 3.1.0
Issue found in Native App or Hybrid App: Native App
OS Version: All
Device: All
Steps to reproduce: Start a chat with a live agent, case/record is not created on the agent side. Agent is not able to get any information of the chat client by using chat entity method of SDK
Actual behavior: Chat agent should side shown with the auto-generated case/record of the user and later on agent should be able to update the case number
Expected Behavior: Chat agent should be shown with auto-generated case number, when chat connects with the agent.
Error Log:

**Comment by rileymacdonald-sf** [comment]
@AndyKD let me investigate this issue further and I'll get back to you with more information.

**Comment by AndyKD** [comment]
yea, please if you don't mind, its little urgent for me, can you investigate and help me out.

Just adding more info I am using 

com.salesforce.service:chat-ui:3.1.0

(if you're only using Live Agent Core, then use com.salesforce.service:chat-core:3.1.0)

from this link : https://developer.salesforce.com/docs/atlas.en-us.service_sdk_android.meta/service_sdk_android/android_install_sdk.htm

**Comment by AndyKD** [comment]
Thanks for your help @rileymacdonald-sf 

From this documentation: https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_chat_send_custom_data.htm

ChatUIConfiguration.Builder not defined anywhere 
 can you please provide me any snippet of code how I can use this?

**Comment by AndyKD** [comment]
I have implemented like below, but still, the case is not getting created automatically at salesforce chat agent side, when my chat connects automatically. The case number to chat agent is showing empty:

protected void initiateChat(ChatConfiguration.Builder chatConfBuilder, Sp_ChatInfoModel data) {
        try {
            ChatUserData firstNameData = new ChatUserData(
                    "FirstName", "Jane", true);
            ChatUserData lastNameData = new ChatUserData(
                    "LastName", "Doe", true);
            ChatUserData emailData = new ChatUserData(
                    "Email", data.getEmail(), true);
            ChatUserData subjectData = new ChatUserData(
                    "Subject", "Live Agent Chat Session", true);

// Map Subject to a field in a Case record
            ChatEntity caseEntity = new ChatEntity.Builder()
                    .showOnCreate(true)
                    .linkToTranscriptField("Case")
                    .addChatEntityField(
            new ChatEntityField.Builder()
                    .doFind(true)
                    .isExactMatch(true)
                    .doCreate(true)
                    .build("Subject", subjectData))
                    .build("Case");

// Map FirstName, LastName, and Email to fields in a Contact record
            ChatEntity contactEntity = new ChatEntity.Builder()
                    .showOnCreate(true)
                    .linkToTranscriptField("Contact")
                    .linkToAnotherSalesforceObject(caseEntity, "Case")
                    .addChatEntityField(
            new ChatEntityField.Builder()
                    .doFind(true)
                    .isExactMatch(true)
                    .doCreate(true)
                    .build("FirstName", firstNameData))
                    .addChatEntityField(
            new ChatEntityField.Builder()
                    .doFind(true)
                    .isExactMatch(true)
                    .doCreate(true)
                    .build("LastName", lastNameData))
                    .addChatEntityField(
            new ChatEntityField.Builder()
                    .doFind(true)
                    .isExactMatch(true)
                    .doCreate(true)
                    .build("Email", emailData))
                    .build("Contact");

// Create the chat configuration builder
            final ChatConfiguration.Builder chatConfigurationBuilder =
            new ChatConfiguration.Builder(data.getCHAT_ORG_ID(), data.getChat_category(),
                    data.getCHAT_DEPLOYMENT_ID(), data.getCHAT_LIVEAGENT_POD());

// Add user data and entities
            chatConfigurationBuilder
                    .chatUserData(firstNameData, lastNameData, emailData, subjectData)
                    .chatEntities(caseEntity, contactEntity);

// Build the chat configuration object
            ChatConfiguration chatConfiguration = chatConfigurationBuilder.build();
            ChatUIConfiguration.Builder builder = new ChatUIConfiguration.Builder().chatConfiguration(chatConfiguration).disablePreChatView(true);
            ChatUIConfiguration chatUIConfiguration = builder.build();

            // Create a core configuration instance
                    ChatUI.configure(chatUIConfiguration)
                            .createClient(context).onResult(new Async.ResultHandler<ChatUIClient>() {
                        @Override
                        public void handleResult(Async<?> operation,
                                                 @NonNull final ChatUIClient chatUIClient) {
                            if (context != null && serialNumber != null && productItem != null) {
                                chatUIClient.addSessionStateListener(new Sp_NetgearChatSessionListener(context, serialNumber, productItem.getProduct()));
                            }
                            chatUIClient.startChatSession(getActivity());
                            if (progressDialog != null && progressDialog.isShowing()) {
                                progressDialog.dismiss();
                            }
                        }
                    });
        } catch (Exception e) {
            if (progressDialog != null && progressDialog.isShowing()) {
                progressDialog.dismiss();
            }
            System.err.printf(TAG, e);
        }
    }

**Comment by AndyKD** [comment]
pre cat pop is disabled Thanks for that. But the main problem is the automatic case is not getting generated.

**Comment by AndyKD** [comment]
I tried with both lighting experience and sales force classic. 
Yes I am able to see the first name now, but case number is not I am able to see

**Comment by AndyKD** [comment]
![chatagent](https://user-images.githubusercontent.com/6467643/44112717-bf791c52-9fba-11e8-8f2b-5b2e4c840412.png)

Please refer this snapshot, In attach record Case is showing as empty.

**Comment by rileymacdonald-sf** [comment]
@AndyKD Can you please confirm if this issue is reproducible with Omni routing or also with Live agent ?

**Comment by AndyKD** [comment]
with Omni channel routing issue is reproducible

**Comment by AndyKD** [comment]
We were able to reproducible with both Actually, omnichannel and live agents. We checked with omnichannel as well as live agents.

**Comment by AndyKD** [comment]
Do you can please provide me any snippet of code where it's running for you or you are able to create a record using android at salesforce chat agent side.

**Comment by rileymacdonald-sf** [comment]
@AndyKD I went ahead and created a [new branch riley/case_creation_test](https://github.com/rileymacdonald-sf/ServiceSDK-Android/tree/riley/case_creation_test) using this sample app containing the code example you've requested. Here is a summary of the changes I've made to verify this functionality:
* `SupportHomeViewAddition.java` now calls `disablePreChatView` to ensure pre chat doesn't pop.
* `ServiceSDKUtils.java` method `getChatConfigurationBuilder()` now creates `ChatUserData`, `ChatEntityField` and `ChatEntity` for `ChatConfiguration.Builder` and passes the data into the `ChatConfiguration.Builder`.

I've verified that starting a live agent chat session on my org using this branch automatically creates a case with the user data containing a Description of "Description Data" and a Subject of "Subject Data".

You can see a detailed diff of the code changes [here](https://github.com/forcedotcom/ServiceSDK-Android/compare/master...rileymacdonald-sf:riley/case_creation_test).

Please verify the issue is reproducible using this code. If the issue is reproducible it's possible the source of the problem is related to the org or it's configuration.

**Comment by AndyKD** [comment]
Hi @rileymacdonald-sf 

Did you shipped the right code to a branch. I am not able to see the changes which mentioned in the above link in the branch you shared with us.

But still from the changes I tried to get all the changes in my code, but still case is not getting created in the sales force automatically.

The other thing is by using the same org id we are able to create the case automatically using iOS and web. If its possible can you please give me zoom session or sykyep?

my skype address is deepak.kumar3038

Would be really appreciated.

**Comment by rileymacdonald-sf** [comment]
@AndyKD I pushed the code to https://github.com/rileymacdonald-sf/ServiceSDK-Android/tree/riley/case_creation_test which is a fork of this repository. If you're unable to checkout the branch it's likely because you haven't cloned the fork or added it as a remote. The simplest solution would be to clone my work and checkout the branch from there:

```bash
$ cd [path_for_clone]
$ git clone git@github.com:rileymacdonald-sf/ServiceSDK-Android.git
$ cd [path_for_clone]/forcedotcom/ServiceSDK-Android/Examples/SnapinsSDKExample/
$ git checkout riley/case_creation_test
```

Please let me know if you're able to checkout my branch and verify the issue is still happening.

**Comment by AndyKD** [comment]
@rileymacdonald-sf Thanks a lot for your support! Really appreciated 
this works for us.

Awsome!

**Comment by jainvishakha** [comment]
I was following this thread, and its working for me to create a case when chat is initiated with an agent. But I am facing a problem when I can start a chat salesforce is not creating a new case instead it will link it with the last existing case.
One more strange behaviour is that when I am passing a customer chat parameter "Priority" with different value then it is creating a new case always but if I am passing the same value for e.g "High". Its only creating the case single time with priority high but next time when chat is initiated it always links with the existing case id with priority high.
Also same thing we have tried in iOS and Web and its working fine there and it always creates a new case when chat is initiated with Live chat agent.

**Comment by rileymacdonald-sf** [comment]
@jainvishakha Are you able to reproduce the issue on your org using this sample application?

**Comment by jainvishakha** [comment]
Yes we are facing the same issue in this sample app too.

**Comment by diegojaka17** [comment]
> @ rileymacdonald-sf ¡ Muchas gracias por su apoyo! Realmente apreciamos que 
> esto funcione para nosotros.
> 
> Impresionante!

Could you share the code you implemented in android to solve the problem?

**Comment by diegojaka17** [comment]
thanks for your help
