### ISSUE TITLE
doesn't display case list view when empty

### ISSUE THREAD

**Issue by SanjeevGopalan** [forcedotcom/ServiceSDK-Android#74]
With the latest version of SnapIn SDK (v214.0.1), the case list view is not displaying when there are no cases to display, instead a blank page is being displayed. Anyone else has encountered this situation? Any available solutions?

**Comment by evanisnor** [comment]
Hey @SanjeevGopalan, let me look into this a bit more. Which device and OS version are you seeing this on?

**Comment by SanjeevGopalan** [comment]
Hi @evanisnor, looks like this issue is across device and Android OS versions. We used Google Pixel XL device with Android 8.1.0. It was also tested on Nexus 6P with same Android version (8.1.0). Faced the same issue on both occasions.

**Comment by evanisnor** [comment]
Thanks @SanjeevGopalan, we are able to reproduce the issue. We'll prioritize this work and have a fix out in our next release.

**Comment by SanjeevGopalan** [comment]
Dear @evanisnor ,
Thanks for confirming. Could you advise us when we can expect the next release please?
Thank you,
Sanjeev

**Comment by evanisnor** [comment]
You can expect our next release some time in October. For more information about Salesforce release dates you can check out the [status page](https://status.salesforce.com/). Select which instance your org resides on and then select the "Maintenances" tab.

Cheers!

**Comment by evanisnor** [comment]
Hey @SanjeevGopalan, @ogenez-tu,

To recap on this issue, when an authenticated user presses the Case SDK launch button in your app and they do not have any open cases, they are met with a blank view and the "Create new case" FAB is not visible, which prevents them from opening their first case.

As I mentioned before, we will have a fix for this issue in our next release. The empty notice will be displayed, and the "Create new case" FAB will also be displayed. In the meantime, I'd like to propose the following workaround to help unblock your users when they attempt to open their first case:

Using the CaseClient API, it is possible to query for the total number of cases for a user once they have been authenticated. If there are no open cases, clicking the Case SDK launch button should open the Case Publisher so they can submit one. If there are existing cases, then clicking the launch button should open the Case List. Have a look at the following sample code for reference.

```
void init (final CaseUIClient uiClient) {
  final AtomicInteger numberOfCases = new AtomicInteger();
  getOpenCaseCount(uiClient.getCoreClient(), caseListName).onResult(new Async.ResultHandler<Integer>() {
    @Override public void handleResult (Async<?> operation, @NonNull Integer result) {
      numberOfCases.set(result);
    }
  }).onComplete(new Async.CompletionHandler() {
    @Override public void handleComplete (Async<?> operation) {
      int caseCount = numberOfCases.get();
      if (caseCount > 0) {
        Toast.makeText(MyActivity.this, "Total " + caseCount + " cases", Toast.LENGTH_SHORT).show();
        enableCaseListLaunch(uiClient);
      } else {
        Toast.makeText(MyActivity.this, "User has no cases", Toast.LENGTH_SHORT).show();
        enableCasePublisherLaunch(uiClient);
      }
    }
  });
}

/**
 * Query Salesforce for the number of cases for the current user, given a case list name.
 * Use ".onResult" to receive the count
 * Use ".onComplete" to toggle your button click action based on the count
 */
private Async<Integer> getOpenCaseCount (final CaseClient caseClient, String caseListName) {
  return caseClient.getListViewDescribe(ListViewDescribeRequest.create(caseListName))
      .chain(new Function<ListViewDescribe, Async<List<CaseListRecord>>>() {
        @Override public Async<List<CaseListRecord>> apply (ListViewDescribe listViewDescribe) {
          return caseClient.getCaseList(CaseListRequest.create(listViewDescribe.getFilterCondition()));
        }
      }).map(new Function<List<CaseListRecord>, Integer>() {
        @Override public Integer apply (List<CaseListRecord> caseList) {
          return caseList.size();
        }
      });
}

private void enableCaseListLaunch (final @NonNull CaseUIClient uiClient) {
  launchButton.setOnClickListener(new View.OnClickListener() {
    @Override public void onClick (View v) {
      uiClient.launchCaseList(MyActivity.this);
    }
  });
}

private void enableCasePublisherLaunch (final @NonNull CaseUIClient uiClient) {
  launchButton.setOnClickListener(new View.OnClickListener() {
    @Override public void onClick (View v) {
      uiClient.launchCasePublisher(MyActivity.this);
    }
  });
}
```

I hope this helps. Cheers!
Evan

**Comment by ogenez-tu** [comment]
Hi Evan,

We'll investigate how/if we can implement this workaround.

Thank you for looking into it!
