### ISSUE TITLE
Remove repeating knowledge title at knowledge ui

### ISSUE THREAD

**Issue by proudchild** [forcedotcom/ServiceSDK-Android#75]
Hello,
Our knowledge base consist of smalls solutions, 
on the mobile, the sdk repeats the solution title as per print attached.

Is there a way to remove it by configuration or method call?

att,
![screenshot_20180816-134335](https://user-images.githubusercontent.com/3269176/44222594-6eee3180-a15b-11e8-9176-62495d6cf018.jpg)

**Comment by rileymacdonald-sf** [comment]
@proudchild Let me investigate this and I'll get back to you with more information.

**Comment by rileymacdonald-sf** [comment]
@proudchild I'm unable to reproduce this issue. I attempted to reproduce the issue by creating a new article and providing data to all the available fields. Is it possible this issue is due to a configuration issue (such as putting the title into the field layout)?

**Comment by rileymacdonald-sf** [comment]
Closing as needs more information.
