### ISSUE TITLE
Attach pdf on live agent SDK

### ISSUE THREAD

**Issue by proudchild** [forcedotcom/ServiceSDK-Android#76]
Hello,

On our app we need to be able to attach to the live agent operator a pdf with the instructions or documents from the client,

But we were only able to attach a image on android.

Is there a way to attach a pdf?
Is there a configuration we can do that?

thanks.

**Comment by rileymacdonald-sf** [comment]
@proudchild We only support uploading images to Live Agent. PDF uploads are not supported.
