### ISSUE TITLE
View all cases and reply back on the case

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/ServiceSDK-Android#77]
Hi Team,

First of all a tons of thanks for your support!

I have one requirement which automated case is getting created at the chat agent side at the time of the live chat. I want to view all the cases related to my product and reply from the same.

This mean I want to see the history of the comments regard to that case and reply for the same. Can I do that can you please help me?

Is there code sample code or snippet is available?

**Comment by rileymacdonald-sf** [comment]
@AndyKD Can you please clarify; is this requirement you're requesting on the org/agent side?

**Comment by AndyKD** [comment]
No on the application client side I am looking for.

**Comment by AndyKD** [comment]
My requirement is like I want to view all the history or comments related to my case and I want to add new comment, Is it possible?

**Comment by rileymacdonald-sf** [comment]
@AndyKD The Chat SDK currently don't support displaying information regarding the history or comments related to cases. I will make a note of your desire for this feature.

**Comment by AndyKD** [comment]
Is there any expectation I can get this by any feature planned release.

**Comment by rileymacdonald-sf** [comment]
@AndyKD please contact your account team directly or make a post at http://ideas.salesforce.com/ regarding this feature request.
