### ISSUE TITLE
Attaching images/snapshot and files with the cases

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/ServiceSDK-Android#78]
Hi Salesforce team,

Thanks for your great help and support!

I am not able to find the code where I can attach the files with the case/record. Do you have any sample available that I can do by my self?

Thanks.

**Comment by rileymacdonald-sf** [comment]
@AndyKD If you're using the default UI, no coding is necessary in your app to get this behavior. However, if you're using the [Core API](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_chat_core_api.htm#android_chat_core_api) please follow our [Transfer File to Agent documentation](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_chat_file_transfer.htm) for implementation instructions.

**Comment by AndyKD** [comment]
Do you have any working example or code snippet to send the file using Android class?

**Comment by rileymacdonald-sf** [comment]
@AndyKD Is the file transfer feature not working for you?

**Comment by AndyKD** [comment]
We are not able to see the attachment option to attach file, Is there anything like if chat agent will request only then client can see the option to attach file or by default this option to attach file is available for the chat users?

**Comment by rileymacdonald-sf** [comment]
@AndyKD Are you indicating that the agent is unable to request a file transfer from the console?

In order for the agent to request a file transfer from the user the live agent chat session needs to be attached to a case.

If you think this is a bug please specify the exact steps you're following to reproduce the issue along with the device details.

Thanks

**Comment by AndyKD** [comment]
No no agent is able to request and on the mobile side we are able to see the camera option as well
but it's saying the in the mobile side, Permission is not there when we are choosing a picture from gallary.

But my application is having the permission of camera.

**Comment by rileymacdonald-sf** [comment]
@AndyKD Please provide more information about the device this issue is reproducible on (device name, Android OS, etc). Have you tried clearing all the application data and reproducing? Are there any additional steps to reproduce the problem?

**Comment by AndyKD** [comment]
I will attach the snapshot, surely
