### ISSUE TITLE
How to display the mobile screen only on the back camera image when connect to SOS like SOS version 1.4.0.

### ISSUE THREAD

**Issue by tkuwada** [forcedotcom/ServiceSDK-Android#80]
**In the latest SOS version 4.0.2,** 
small windows are displayed in the large window and the lower right when connecting with SOS.

Camera images displayed on mobile are as follows.

[Mobile screen]
· Large window: Operator's camera image
· Small window: video of the back camera

[Operator's screen]
・Mobile side back camera video

The support requirement of SOS changed this time, it was necessary to raise the version of SOS, and it occurred when trying.

Previously we used **SOS version 1.4.0.**
In this version, camera images displayed on the mobile phone at the time of connection are as follows.

[Mobile screen]
· Large window: video of the back camera
· Small window: **not exist**

[Operator's screen]
・Mobile side back camera video

If you can not hide small windows with SOS specifications, 
please tell me how to display the back camera image in large windows by default when connecting to SOS.

Best regards.

**Comment by evanisnor** [comment]
Hey @tkuwada, thanks for posting. Can you answer a few questions for me?
1. Which device and OS version are you testing on?
2. What does your `SosConfiguration.Builder` code look like? Can you share it with me?

Thanks,
Evan

**Comment by tkuwada** [comment]
Hi @evanisnor, thank you for replying.

>1. Which device and OS version are you testing on? 

Android API version 21 and 28. 
Actually, I would like to use it in API version 16, but the support requirement changed in May 2018, 
the min API version was changed to 21, and it became unusable.

 <br>

>2.  What does your SosConfiguration.Builder code look like? Can you share it with me?

```
SosConfiguration configuration = new SosConfiguration.Builder()`
        .twoWayVideo(true)
        .onboardingUi(false) 
        .frontFacingCamera(false)  //unused it
        .backFacingCamera(true) 
        .audio(false)              //unused it
        .fieldServices(true)
        .playSounds(true)
        .agentPublish(true)
        .permissionUi(false) 
```

**Comment by tkuwada** [comment]
Attached a schematic overview of the problem.

<br>

![img_sos_connecting_ver4 0 2](https://user-images.githubusercontent.com/11694610/44695286-7099ec80-aaad-11e8-8e41-c8ffc548249b.png)



It is not our desired specification that the video of the agent is displayed.
In our use case, the agent does not use web camera and audio.

I hope to display only the back camera image on the mobile screen, and do not use the mobile of face camera.

**Comment by evanisnor** [comment]
Hey @tkuwada, thanks for being so concise with your question. The diagram is very appreciated! Unfortunately hiding the agent video is not supported in the SOS Android SDK.

Cheers,
Evan

**Comment by tkuwada** [comment]
Hi @evanisnor , I understand that it can not be done with the current SOS version.

However, in SOS version 1.4.0 the agent was hidden and the application was running. 
Please tell me which version changed specifications and how I should have detected it.

Best,
Toshiyasu
