### ISSUE TITLE
Migrate v4 FragmentActivity to v7 FragmentActivity

### ISSUE THREAD

**Issue by bartolkaruza** [forcedotcom/ServiceSDK-Android#87]
The required superclass of an Activity for the call to `.startChatSession()` is a support v4 `FragmentActivity`. The minimum SDK version for the SF Mobile SDK is 21, making the v4 `FragmentActivity` super class unnecessary. The preferred superclass should be the `AppCompatActivity`. Keeping the v4 FragmentActivity will prevent any React Native apps RN < 0.57 from integrating the ServiceSDK easily in addition to it forcing every app to include an obsolete support library.

https://github.com/facebook/react-native/pull/20602

**Comment by evanisnor** [comment]
Hey @bartolkaruza, thanks for bringing this up. We'll look into this and see what we can do.

Cheers,
Evan
