### ISSUE TITLE
Picklist sort order is alphabetical in v214.0.2, while it should be based on the order set in Salesforce

### ISSUE THREAD

**Issue by SanjeevGopalan** [forcedotcom/ServiceSDK-Android#88]
When using v214.0.2, the values in picklist fields are shown in alphabetical order while it should be shown in the order that is defined in Salesforce. This is an issue in this version, while in previous versions the order is per what is defined in Salesforce. This has high impact on us since the users tend to chose first few items and the first in alphabetical order is something we want down in the order.
The workaround is not acceptable for us since any changes to the picklist values affects the iOS version as well and there are some process flows, visual flows etc that uses these picklist values which will also needs to be updated if we make any changes to the picklist values. 
Issue affects version https://github.com/forcedotcom/ServiceSDK-Android/releases/tag/214.0.2

**Comment by rileymacdonald-sf** [comment]
Thanks for raising this @SanjeevGopalan. Closing this issue as we're now tracking this bug internally.
