### ISSUE TITLE
New case not created when initiating a new chat with live agent. Linkning with existing case.

### ISSUE THREAD

**Issue by jainvishakha** [forcedotcom/ServiceSDK-Android#98]
Salesforce creating a case when chat is initiated with a live agent. But I am facing a problem when I can start a chat salesforce is not creating a new case instead it will link it with the last existing case.

One more strange behaviour is that when I am passing a customer chat parameter "Priority" with different value then it is creating a new case always but if I am passing the same value for e.g "High". Its only creating the case single time with priority high but next time when chat is initiated it always links with the existing case id with priority high.
Also same thing we have tried in iOS and Web and its working fine there and it always creates a new case when chat is initiated with Live chat agent.

_Originally posted by @jainvishakha in https://github.com/forcedotcom/ServiceSDK-Android/issue_comments#issuecomment-434630659_

**Comment by rileymacdonald-sf** [comment]
@jainvishakha Are you able to reproduce the issue on your org using this sample application?

**Comment by jainvishakha** [comment]
Yes issue is reproducible in sample app too.

**Comment by rileymacdonald-sf** [comment]
> Salesforce creating a case when chat is initiated with a live agent. But I am facing a problem when I can start a chat salesforce is not creating a new case instead it will link it with the last existing case.

@jainvishakha Can you please verify what builder arguments you're using with `ChatEntityField.Builder()`. Are you using `.doFind(true)` or `.isExactMatch(true)`?

**Comment by jainvishakha** [comment]
Yes, I am using .doFind(true) ,  .isExactMatch(true), .doCreate(true) with ChatEntityField.Builder()

**Comment by rileymacdonald-sf** [comment]
This functionality appears to be working as expected. See the API reference at https://forcedotcom.github.io/ServiceSDK-Android/releases/chat/3.2.0/api/reference/com/salesforce/android/chat/core/model/ChatEntityField.Builder.html:

> `doFind()`: Define whether or not this ChatEntityField will perform a lookup query for records that match the ChatUserData value within the specified Salesforce object field.

> `isExactMatch(true)`: Define whether or not the lookup should match Salesforce record results based on an exact match with the value provided by ChatUserData.

If you remove `doFind(true)` and `isExactMatch(true)` I assume a new case will be created as expected. Is the code you posted in issue #101 the same as what you're referring to here?

**Comment by jainvishakha** [comment]
Yes, Its works for me. Thanks for your great help !!
