### ISSUE TITLE
Receiving ChatID and CaseID via Android SDK

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/ServiceSDK-Android#99]
After every chat ends, we would like to direct customer to a rating page, in which after customer has rated us, the result will be sent back to be associated with chat/case raised by customer.

To do so, caseID and chatID is needed to correctly link result and its case, however, right now the SDK only know agentID.

Any advice on how to pass caseID and chatID via SDK?

Version of Mobile SDK Used: SDK version: 214.0.2, Live agent chat version: 3.1.0
Issue found in Native App or Hybrid App: Native App

**Comment by evanisnor** [comment]
Hi @JinTiloganart, unfortunately it is not possible for the Chat SDK to relay the Case ID to the client.

Cheers!
Evan

**Comment by JinTiloganart** [comment]
Hi @evanisnor , is it possible to pass chat id?

**Comment by evanisnor** [comment]
It looks like the chat transcript ID is not passed to the Chat SDK either, so it is not possible for the SDK to pass it to the app. Sorry about that!

**Comment by JinTiloganart** [comment]
Hi @evanisnor , can you recommend what can we do if we want to link the survey result that we capture to the correct chat transcript or case on Salesforce?

**Comment by evanisnor** [comment]
Unfortunately I can't help you with that. I can only help you with issues directly related to the Android Snap-ins SDK. Please reach out Customer Success; they should have people who are better equipped to help you find a solution.

Cheers,
Evan
